apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
    role: alert-rules
data:
  prometheus.rules.yaml: |
    groups:
      - name: deployment-alerts
        rules:
          - alert: GitOpsDeployment
            expr: changes(kube_deployment_status_replicas{namespace="default"}[1m]) > 0
            for: 1m
            labels:
              severity: info
            annotations:
              summary: "Deployment done via GitOps"
              description: "A deployment has been done via the GitOps repository."

      - name: service-health-alerts
        rules:
          - alert: ServiceUnhealthy
            expr: kube_pod_status_phase{phase="Failed"} > 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Service Unhealthy"
              description: "A service is unhealthy in the cluster."
