serverFiles:
  alerting_rules.yml:
    groups:
      - name: NodeDown
        rules:
          - alert: InstanceDown
            expr: up{job="kubernetes-nodes"} == 0
            for: 2m
            labels:
              severity: page
            annotations:
              host: "{{ $labels.kubernetes_io_hostname }}"
              summary: "Instance down"
              description: "Node {{ $labels.kubernetes_io_hostname }} has been down for more than 5 minutes."

      - name: low_memory_alert
        rules:
          - alert: LowMemory
            expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 85
            for: 2m
            labels:
              severity: warning
            annotations:
              host: "{{ $labels.kubernetes_node }}"
              summary: "{{ $labels.kubernetes_node }} Host is low on memory. Only {{ $value }}% left"
              description: "{{ $labels.kubernetes_node }} node is low on memory. Only {{ $value }}% left"

          - alert: KubePersistentVolumeErrors
            expr: kube_persistentvolume_status_phase{job="kubernetes-service-endpoints",phase=~"Failed|Pending"} > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              description: The persistent volume {{ $labels.persistentvolume }} has status {{ $labels.phase }}.
              summary: PersistentVolume is having issues with provisioning.

          - alert: GitOpsDeployment
            expr: changes(kube_deployment_status_replicas_updated{job="kubernetes-service-endpoints"}[5m]) > 0
            for: 2m
            labels:
              severity: info
            annotations:
              summary: "Deployment via GitOps detected"
              description: "A deployment has been made via the GitOps repo in the last 5 minutes."

          - alert: ServiceUnhealthy
            expr: up{job="kubernetes-service-endpoints",status="unhealthy"} == 1
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Service is unhealthy"
              description: "Service {{ $labels.service }} is unhealthy."
