serverFiles:
  alerting_rules.yml:
    groups:
      - name: NodeDown
        rules:
          - alert: InstanceDown
            expr: up{job="kubernetes-nodes"} == 0
            for: 2m
            labels:
              severity: page
            annotations:
              host: "{{ $labels.kubernetes_io_hostname }}"
              summary: "Instance down"
              description: "Node {{ $labels.kubernetes_io_hostname }} has been down for more than 5 minutes."

          - alert: GitOpsDeployment
            expr: changes(kube_deployment_status_replicas_updated{job="kubernetes-service-endpoints"}[5m]) > 0
            for: 2m
            labels:
              severity: info
            annotations:
              summary: "Deployment via GitOps detected"
              description: "A deployment has been made via the GitOps repo in the last 5 minutes."

          - alert: ServiceUnhealthy
            expr: up{job="kubernetes-service-endpoints",status="unhealthy"} == 1
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Service is unhealthy"
              description: "Service {{ $labels.service }} is unhealthy."
