grafana:
  grafana.ini:
    assertNoLeakedSecrets: false
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: sdaman830@gmail.com
      password: password
      cert_file:
      key_file:
      from_address: sdaman830@gmail.com
      from_name: Grafana
      skip_verify: false
      ehlo_identity:
      startTLS_policy:

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: gmail
      routes:
        - receiver: gmail
          matchers:
            - alertname =~ "TargetDown|KubeSchedulerDown|Watchdog"
    receivers:
      - name: gmail
        email_configs:
          - to: sdaman830@gmail.com
            from: sdaman830@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: sdaman830@gmail.com
            auth_identity: sdaman830@gmail.com
            auth_password: password
            send_resolved: true
    templates:
      - "/etc/alertmanager/config/*.tmpl"
